version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - kalinon
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "gulfcoastdevops/goreviewer"
      - kalinon
      - caseiber
      - ES0T
    groups:
      go-group-all:
        patterns:
          - "*"  # Group all Go module updates into one PR  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "gulfcoastdevops/goreviewer"
      - kalinon
