# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
#    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    main: cmd/manager/main.go
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - config/**/*
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  name_template: "v{{.Version}}"
  extra_files:
    - glob: default.yaml
    - glob: crds.yaml
#dockers:
#  - goos: linux
#    goarch: amd64
#    dockerfile: hack/goreleaser/Dockerfile
#    image_templates:
#      - "656688821056.dkr.ecr.us-east-1.amazonaws.com/keycloak-operator:v{{ .Version }}"
#      - 656688821056.dkr.ecr.us-east-1.amazonaws.com/keycloak-operator:latest
#      - "ghcr.io/gulfcoastdevops/keycloak-operator:v{{ .Version }}"
#      - ghcr.io/gulfcoastdevops/keycloak-operator:latest
#    use: buildx
#    build_flag_templates:
#      - "--platform=linux/amd64"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 1
