name: release
on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /
    branches:
      - 'main'
  pull_request:
permissions: write-all
jobs:
  goreleaser:
    uses: gulfcoastdevops/workflow-templates/.github/workflows/goreleaser-job.yml@main
    secrets: inherit
  build:
    needs: goreleaser
    uses: gulfcoastdevops/workflow-templates/.github/workflows/docker-build-push.yml@main
    with:
      image-name: keycloak-operator
      context: ./dist/keycloak-operator_linux_amd64_v1
      dockerfile: ./hack/goreleaser/Dockerfile
    secrets: inherit
